openapi: 3.1.0
info:
  title: Food Orders API
  description: |-
    Food Orders API for managing ingredients, menu items, and orders.
  #
  #    Security:
  #    Oauth 2
  version: 1.0.0
  #  termsOfService: https://swagger.io/terms/
  contact:
    email: oliverpelhamdev@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
#externalDocs:
#  description: Find out more about Swagger
#  url: https://swagger.io
servers:
  - url: https://oliverpelham.dev/food-orders/api/v1
tags:
  - name: ingredients
    description: Manage ingredient items
  - name: menu-items
    description: Manage menu items
  - name: orders
    description: Manage orders
paths:
  /ingredients:
    post:
      tags:
        - ingredients
      summary: Add a New Ingredient.
      description: Add a new ingredient type to inventory.
      operationId: addIngredient
      parameters:
        - $ref: '#/components/parameters/CorrelationIdHeader'
      requestBody:
        description: Create a new ingredient in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientRequest'
            examples:
              sample:
                $ref: '#/components/examples/IngredientRequest'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddIngredientResponse'
              examples:
                sample:
                  $ref: '#/components/examples/AddIngredientResponse'
        '400':
          $ref: "#/components/responses/Error400"
        '401':
          $ref: "#/components/responses/Error401"
        '404':
          $ref: "#/components/responses/Error404"
        '409':
          $ref: "#/components/responses/Error409"
        '500':
          $ref: "#/components/responses/Error500"

  #      security:
  #        - food_orders_auth:
  #            - write:ingredients
  #            - read:ingredients

  /ingredients/findByAvailability:
    get:
      tags:
        - ingredients
      summary: Find Ingredients by Availability Status.
      description: Multiple tags can be provided with comma separated strings. Use "?availability=UNAVAILABLE,AVAILABLE".
      operationId: findIngredientsByAvailability
      parameters:
        - $ref: '#/components/parameters/CorrelationIdHeader'
        - name: availability
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: false #todo check this
          schema:
            type: string
            default: AVAILABLE
            enum:
              - AVAILABLE
              - UNAVAILABLE
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientsList' #todo add any other high level fields?
              examples:
                sample:
                  $ref: '#/components/examples/IngredientsList'
        '400':
          $ref: "#/components/responses/Error400" #todo refer to responses then schemas within?
        '401':
          $ref: "#/components/responses/Error401"
        '404':
          $ref: "#/components/responses/Error404"
        '500':
          $ref: "#/components/responses/Error500"

  #      security:
  #        - food_orders_auth:
  #            - read:ingredients

  /ingredients/{ingredientId}:
    get:
      tags:
        - ingredients
      summary: Get an Ingredient by ID.
      description: Returns a single ingredient.
      operationId: getIngredientById
      parameters:
        - $ref: '#/components/parameters/CorrelationIdHeader'
        - $ref: '#/components/parameters/IngredientId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientResponse'
              examples:
                sample:
                  $ref: '#/components/examples/IngredientResponse'
        '400':
          $ref: "#/components/responses/Error400"
        '401':
          $ref: "#/components/responses/Error401"
        '404':
          $ref: "#/components/responses/Error404"
        '500':
          $ref: "#/components/responses/Error500"
    #      security:
    #        - food_orders_auth:
    #            - read:ingredients

    put:
      tags:
        - ingredients
      summary: Update Ingredient by ID.
      description: Edit an ingredient type.
      operationId: updateIngredient
      parameters:
        - $ref: '#/components/parameters/CorrelationIdHeader'
        - $ref: '#/components/parameters/IngredientId'
      requestBody:
        description: Update an existing ingredient
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientRequest'
            examples:
              sample:
                $ref: '#/components/examples/IngredientRequest'
      responses:
        '204':
          description: Successful operation
        '400':
          $ref: "#/components/responses/Error400"
        '401':
          $ref: "#/components/responses/Error401"
        '404':
          $ref: "#/components/responses/Error404"
        '409':
          $ref: "#/components/responses/Error409"
        '500':
          $ref: "#/components/responses/Error500"

    delete:
      tags:
        - ingredients
      summary: Deletes an Ingredient by ID.
      description: Delete an ingredient.
      operationId: deleteIngredient
      parameters:
        - $ref: '#/components/parameters/CorrelationIdHeader'
        #        - name: api_key
        #          in: header
        #          description: ''
        #          required: false
        #          schema:
        #            type: string
        - $ref: '#/components/parameters/IngredientId'
      responses:
        '204':
          description: Successful operation
        '400':
          $ref: "#/components/responses/Error400"
        '401':
          $ref: "#/components/responses/Error401"
        '404':
          $ref: "#/components/responses/Error404"
        '500':
          $ref: "#/components/responses/Error500"
#      security:
#        - petstore_auth:
#            - write:pets
#            - read:pets

components:
  schemas:
    IngredientRequest:
      required: # todo find out about mandatory for response fields
        - name
        - quantity
        - category
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 20
        quantity:
          type: integer
        category:
          type: string
          description: Storage Category of this ingredient
          enum:
            - FROZEN
            - CHILLED
            - DRY_GOOD
    
    IngredientResponse:
      required:
        - ingredientId
        - name
        - quantity
        - category
      type: object
      additionalProperties: false
      properties:
        ingredientId:
          type: string
          description: Unique identifier of this ingredient.
          readOnly: true
          format: uuid
        name: #todo add length check on all request and parameterise
          type: string
        quantity:
          type: integer
        category:
          type: string
          description: Storage Category of this ingredient
          enum:
            - FROZEN
            - CHILLED
            - DRY_GOOD
        availability:
          type: string
          description: System generated availability status.
          readOnly: true
          enum:
            - AVAILABLE
            - UNAVAILABLE

    IngredientsList:
      type: array
      items:
        $ref: '#/components/schemas/IngredientResponse'

    AddIngredientResponse:
      required:
        - ingredientId
      type: object
      additionalProperties: false
      properties:
        ingredientId:
          type: string
          description: Unique identifier of this ingredient.
          readOnly: true
          format: uuid

    Error:
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
        error:
          type: string
        statusCode:
          type: number
      required:
        - message
        - error
        - statusCode

  responses:
    Error400:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            sample:
              value:
                {
                  "message": "Bad Request",
                  "error": "BadRequestError",
                  "statusCode": 400
                }
    Error401:
      description: Unauthorised
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            sample:
              value:
                {
                  "message": "Unauthorized",
                  "error": "UnauthorizedError",
                  "statusCode": 401
                }
    Error404:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            sample:
              value:
                {
                  "message": "Not Found",
                  "error": "NotFoundError",
                  "statusCode": 404
                }
    Error409:
      description: Conflict error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            sample:
              value:
                {
                  "message": "Ingredient Already Exists",
                  "error": "ConflictError",
                  "statusCode": 409
                }
    Error500:
      description: General error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            sample:
              value:
                {
                  "message": "Internal Server Error",
                  "error": "InternalServerError",
                  "statusCode": 500
                }

  examples:
    IngredientRequest:
      summary: Sample request body
      value:
        name: Tomato
        quantity: 5
        category: CHILLED
    IngredientResponse:
      summary: sample response body
      value:
        ingredientId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        name: Tomato
        quantity: 5
        category: CHILLED
        availability: AVAILABLE
    AddIngredientResponse:
      summary: sample response body
      value:
        ingredientId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
    IngredientsList:
      summary: sample response body
      value:
        - ingredientId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
          name: Tomato
          quantity: 5
          category: CHILLED
          availability: AVAILABLE
        - ingredientId: 8cf2d12b-bb75-4a13-996f-d72b7ed2fb2b
          name: Lettuce
          quantity: 12
          category: DRY_GOOD
          availability: AVAILABLE
    Error400:
      summary: A 400 error
      value:
        {
          "message": "Bad Request",
          "error": "BadRequestError",
          "statusCode": 400
        }
    Error401:
      summary: A 401 error
      value:
        {
          "message": "Unauthorized",
          "error": "UnauthorizedError",
          "statusCode": 401
        }
    Error404:
      summary: A 404 error
      value:
        {
          "message": "Not Found",
          "error": "NotFoundError",
          "statusCode": 404
        }
    Error409:
      summary: A 409 error
      value:
        {
          "message": "Ingredient Already Exists",
          "error": "ConflictError",
          "statusCode": 409
        }
    Error500:
      summary: A 500 error
      value:
        {
          "message": "Internal Server Error",
          "error": "InternalServerError",
          "statusCode": 500
        }

  parameters:
    CorrelationIdHeader:
      name: correlation-id
      in: header
      required: true
      description: A UUID used for request tracing.
      example: a58bdc-555a-4980-b779-355fc7e27cb5
      schema:
        type: string
        format: uuid

    IngredientId:
      name: ingredientId
      in: path
      description: This ingredients ID
      required: true
      example: a58bdc-555a-4980-b779-355fc7e27cb5
      schema:
        type: string
        format: uuid

#  securitySchemes:
#    food_orders_auth:
#      type: oauth2
#      flows:
#        implicit:
#          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
#          scopes:
#            "write:ingredients": modify pets in your account
#            "read:ingredients": read your pets
#    api_key:
#      type: apiKey
#      name: api_key
#      in: header